name: weather
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  location: "^1.1.7"
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Rubik Mono One
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
  assets:
    - assets/icons/clear-day.png
    - assets/icons/clear-night.png
    - assets/icons/rain.png
    - assets/icons/snow.png
    - assets/icons/sleet.png
    - assets/icons/wind.png
    - assets/icons/fog.png
    - assets/icons/cloudy.png
    - assets/icons/partly-cloudy-day.png
    - assets/icons/partly-cloudy-night.png
    - assets/icons/hail.png
    - assets/icons/thunderstorm.png
    - assets/icons/tornado.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
